esphome:
  name: test-sequencer

esp32:
  board: esp32dev
  framework:
    type: arduino

# Required due to local component testing
external_components:
  - source:
      type: local
      path: components

logger:

number:
select:
switch:


# Fake light
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO2
    num_leds: 30
    rgb_order: GRB
    name: "Led Strip"
    id: led_strip
    effects:
      - addressable_cfx:
          name: "Rainbow Wipe"
          effect_id: 3 # Wipe
          set_speed: 50

cfx_sequence:
  - id: my_sequencer
    name: "Test Sequence"  
    lights: [ led_strip ]
    effect: "Rainbow Wipe"
    set_speed: 255
    set_intensity: 128
    set_palette: 0
    iterations: 2
    on_start:
      - logger.log: "Sequence started!"
    on_complete:
      - logger.log: "Sequence complete!"
      - cfx_sequence.start:
          id: my_sequencer
    on_reach:
      - position: "50%"
        then:
          - logger.log: "Reached 50%!"
    on_pixel_num:
      - pixel: 10
        then:
          - logger.log: "Passed pixel 10!"
