/*
 * Copyright (c) 2026 Federico Leoni (effelle)
 *
 * CFXVirtualSegmentLight - Zero-copy AddressableLight slice over parent buffer
 * Each instance maps virtual pixel [0..N] to physical pixel [start..stop]
 * in the parent CFXLightOutput's buffer. Enables per-segment light entities.
 */

#pragma once

#ifdef USE_ESP32

#include "cfx_light.h"
#include "esphome/components/light/addressable_light.h"
#include "esphome/core/component.h"

#include <string>

namespace esphome {
namespace cfx_light {

class CFXVirtualSegmentLight : public light::AddressableLight {
public:
  CFXVirtualSegmentLight(CFXLightOutput *parent, uint16_t start, uint16_t stop,
                         const std::string &seg_id)
      : parent_(parent), start_(start), stop_(stop), seg_id_(seg_id) {}

  // --- AddressableLight interface ---

  int32_t size() const override { return stop_ - start_; }

  light::ESPColorView get_view_internal(int32_t index) const override {
    // Zero-copy: access parent's buffer via public operator[]
    return (*parent_)[start_ + index];
  }

  void loop() override {
    light::LightState *st = this->state_parent_;
    bool effect_active = false;
    if (st != nullptr) {
      effect_active = (st->get_effect_name() != "None");
    }

    // BUG FIX: ESPHome's AddressableLight::loop() aggressively overwrites
    // the pixel buffer with `current_values` if a transition (transformer) is
    // active. This causes two critical bugs on virtual segments:
    // 1. Transition Spikes (White flash): When turning ON with an effect, it
    // paints white
    //    for 1s, hiding the effect.
    // 2. Invisible Outros: When turning OFF, it paints black for 1s, constantly
    // overwriting
    //    the outro frames generated by CFXLightOutput::loop().

    if (effect_active || parent_->has_outro()) {
      // By returning early, we bypass the AddressableLight::loop() which paints
      // the strip solid. The effect handles its own schedule_show() timer
      // inside apply(). For Outros, the Master writes the buffer and DMA
      // flushes it directly.
      return;
    }

    // Normal behavior for solid colors (no effect, no outro)
    light::AddressableLight::loop();
  }

  // BUG 8 FIX: The LightState's OFF transition continuously calls
  // update_state(), which paints ALL segment pixels toward black via
  // AddressableLight::update_state(). Since our get_view_internal() is
  // zero-copy into the parent's buffer, this overwrites outro frames
  // before DMA fires. Intercept here to skip painting during outro.
  void update_state(light::LightState *state) override {
    if (parent_->has_outro())
      return;
    light::AddressableLight::update_state(state);
  }

  void write_state(light::LightState *state) override {
    // Delegate DMA to parent via the segment-flush path.
    // Suppress flush while parent has an outro in progress.
    if (parent_->has_outro())
      return;
    parent_->request_segment_flush();
  }

  light::LightTraits get_traits() override {
    auto traits = light::LightTraits();
    // Inherit the physical capabilities of the strip (restore RGB segment
    // controls)
    if (parent_->has_white_channel()) {
      traits.set_supported_color_modes(
          {light::ColorMode::RGB_WHITE, light::ColorMode::WHITE});
    } else {
      traits.set_supported_color_modes({light::ColorMode::RGB});
    }
    return traits;
  }

  void clear_effect_data() override {
    for (int32_t i = 0; i < this->size(); i++)
      parent_->get_effect_data()[start_ + i] = 0;
  }

  float get_setup_priority() const override {
    // After parent setup
    return setup_priority::HARDWARE - 1.0f;
  }

  void setup() override {
    // Nothing to do — parent owns all hardware
  }

  void dump_config() override {
    ESP_LOGCONFIG("cfx_vseg", "  Virtual Segment '%s': LEDs %u-%u (%d pixels)",
                  seg_id_.c_str(), start_, stop_, this->size());
  }

  // --- Segment identity ---

  const std::string &get_segment_id() const { return seg_id_; }
  uint16_t get_start() const { return start_; }
  uint16_t get_stop() const { return stop_; }
  CFXLightOutput *get_parent() const { return parent_; }

protected:
  CFXLightOutput *parent_;
  uint16_t start_;
  uint16_t stop_;
  std::string seg_id_;
};

} // namespace cfx_light
} // namespace esphome

#endif // USE_ESP32
